title: 'UW CSSS508'
description: 'Course website for University of Washington Center for Statistics and the Social Sciences CSSS508: Introduction to R for Social Scientists'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal